name: Jest Tests
on:
    pull_request:
        branches: [ main ]
jobs:
    test:
        runs-on: ubuntu_runner
        steps:
        - uses: actions/checkout@v3
        - name: Setup node js for using jest
          uses: actions/setup-node@v3
          with:
            node-version: '18'
            cache: 'npm'
        - name: Install dependencies
          run: npm ci
          
        - name: Run Jest tests
          run: npm test
